### ISSUE TITLE
[Feature] SMTP Notification for pending reviews

### ISSUE THREAD

**Issue by CloudGoesPwn** [Cirx08/WeddingShare#28]
Hello,

I would highly like a quick smtp notification when reviews are pending, maybe not on upload but at least a daily reminder with the count of pictures that needs reviewing ?

Thanks!

**Comment by Cirx08** [comment]
## Tasks
- [x] Pending item email report based on configurable cron schedule (default to nightly at 00:00 and disabled).
- [x] Smtp notification options.
- [x] Ntfy notification options.
- [x] Gotify notification options.

**Comment by Cirx08** [comment]
This can now be done in v1.4.1 with the new notification keys listed in the readme.md. (too many options to list here)
