### ISSUE TITLE
[Feature] - Gallery Management

### ISSUE THREAD

**Issue by Cirx08** [Cirx08/WeddingShare#6]
## Tasks
- [x] Add a configuration option to prevent guests creating new galleries.
- [x] Migrate away from directory scanning to DB management.
- [x] Allow admin to create a new gallery.
- [x] Allow admin to rename an existing gallery.
- [x] Allow admin to delete an existing gallery.
- [x] Allow admin to download a gallery as a zip.

**Comment by Cirx08** [comment]
Release v1.1.0 is now published.
