### ISSUE TITLE
[Feature] - Add Video Support

### ISSUE THREAD

**Issue by Cirx08** [Cirx08/WeddingShare#8]
## Tasks
- [ ] Allow users to upload video files.
- [ ] Alter the gallery to show video thumbnails.
- [ ] Update lightbox to play videos.

**Comment by Cirx08** [comment]
`v1.4.6` is now released bringing video support - https://docs.wedding-share.org/blog/1.4.6

**Comment by Cirx08** [comment]
@VeniceNerd you can remove the video formats from the allow list.

<img width="312" height="98" alt="Image" src="https://github.com/user-attachments/assets/2117c3b4-34b3-4aab-af74-ea36eabab461" />

**Comment by VeniceNerd** [comment]
> [@VeniceNerd](https://github.com/VeniceNerd) you can remove the video formats from the allow list.
> 
> <img alt="Image" width="312" height="98" src="https://private-user-images.githubusercontent.com/102923275/474992068-2117c3b4-34b3-4aab-af74-ea36eabab461.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ0ODE0NDYsIm5iZiI6MTc1NDQ4MTE0NiwicGF0aCI6Ii8xMDI5MjMyNzUvNDc0OTkyMDY4LTIxMTdjM2I0LTM0YjMtNGFhYi1hZjc0LWVhMzZlYWJhYjQ2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgwNlQxMTUyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzQ1ZDgyZDQ4NjFhMDZkNWE2MjIwOTFlM2MyN2VkOGQyNjBjZWVlYjFmNTczYjliMzA5Y2JkMjkyN2VhZTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WHvypnfHlGqsuGinbCnGDGij1MI6YXW36jESmlPX4m0">

Wow you're fast! I was just editing my post saying that I just changed that to only allow ".jpg, .jpeg, and .png" but it appears the photo picker on iOS will still show video files. Not sure if there is anything on your end that you could do about that, though, as to only allow guests to select photo content.

Also, have you run into these issues with video uploads as well? Would be super cool to make this more reliable but currently it doesn't seem reliable enough? At least I haven't had any success uploading a video around 400MB, for example.
